//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductHistory
    {
        public int Id { get; set; }
        public string Barcode { get; set; }
        public int Unit { get; set; }
        public string NameOld { get; set; }
        public string NameNew { get; set; }
        public Nullable<int> PriceBuyOld { get; set; }
        public Nullable<int> PriceBuyNew { get; set; }
        public Nullable<int> InterestOld { get; set; }
        public Nullable<int> InterestNew { get; set; }
        public Nullable<int> PriceOld { get; set; }
        public Nullable<int> PriceNew { get; set; }
        public Nullable<int> QuantityOld { get; set; }
        public Nullable<int> QuantityNew { get; set; }
        public Nullable<int> CategoryIdOld { get; set; }
        public Nullable<int> CategoryIdNew { get; set; }
        public Nullable<int> SupplierIdOld { get; set; }
        public Nullable<int> SupplierIdNew { get; set; }
        public Nullable<bool> PinOld { get; set; }
        public Nullable<bool> PinNew { get; set; }
        public Nullable<bool> EnableOld { get; set; }
        public Nullable<bool> EnableNew { get; set; }
        public Nullable<System.DateTime> ExpirationDateOld { get; set; }
        public Nullable<System.DateTime> ExpirationDateNew { get; set; }
        public string ImgOld { get; set; }
        public string ImgNew { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public int Status { get; set; }
    }
}
